"""added shop

Revision ID: 34e33b2bd549
Revises: b57327a6a5b3
Create Date: 2022-01-11 00:26:24.337079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e33b2bd549'
down_revision = 'b57327a6a5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_id'), 'shop', ['id'], unique=False)
    op.create_index(op.f('ix_shop_shop_name'), 'shop', ['shop_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_shop_name'), table_name='shop')
    op.drop_index(op.f('ix_shop_id'), table_name='shop')
    op.drop_table('shop')
    # ### end Alembic commands ###
