"""Add subscription fields to store

Revision ID: 5c92e09e509a
Revises: 34e33b2bd549
Create Date: 2022-01-29 18:09:36.200294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c92e09e509a'
down_revision = '34e33b2bd549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('dev_store', sa.Boolean(), nullable=True))
    op.add_column('shop', sa.Column('subscribed', sa.Boolean(), nullable=True))
    op.add_column('shop', sa.Column('free_trial_end', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'free_trial_end')
    op.drop_column('shop', 'subscribed')
    op.drop_column('shop', 'dev_store')
    # ### end Alembic commands ###
