"""Added charge ID col

Revision ID: 8c12a2cf8824
Revises: e4c1fedc77da
Create Date: 2022-02-01 01:24:51.318140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c12a2cf8824'
down_revision = 'e4c1fedc77da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('charge_id', sa.Integer(), nullable=True))
    op.drop_column('shop', 'subscribed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('subscribed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('shop', 'charge_id')
    # ### end Alembic commands ###
