"""Add host to shop

Revision ID: e4c1fedc77da
Revises: 5c92e09e509a
Create Date: 2022-01-30 23:33:40.808650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c1fedc77da'
down_revision = '5c92e09e509a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('host', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'host')
    # ### end Alembic commands ###
